^[Factors by type]
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX type:  <http://rdf.freshwaterlife.org/type/>
PREFIX vocab: <http://rdf.freshwaterlife.org/vocab/>
PREFIX resource:  <http://rdf.freshwaterlife.org/resource/>

SELECT DISTINCT ?type ?graph
{
    GRAPH ?graph 
    {
       ?observation vocab:hasFactor ?factor .
       ?observation vocab:hasSite ?site.
       ?site rdf:type ?type.
      # FILTER (?type != type:site)
    }
}
order by ?type ?factor

